project:
  type: website
  output-dir: docs

website:
  title: ""
  site-url: "https://myesaya.github.io/data-analysis-lab/"
  page-footer:
    left: |
      This website is built in R with ❤️ using [Quarto](https://quarto.org/)
    right: |
     @Blantyre-based freelance consultants; 2025 Data Analysis Lab

  navbar:
    background: "#5b195b"
    logo: "images/logo-4.png"

    left:
      - text: "Home"
        href: index.qmd
      - text: "Past Analysis"
        href: posts/
      - text: "Our prices"
        href: our-prices/
      - text: "Reviews"
        href: reviews
      - text: "Commitments"
        href: privacy-policy/


    right:
      - icon: whatsapp
        href: "https://wa.me/265884501024?text=Hi%20Data%20Analysis%20Lab,%20can%20you%20help%20analyse%20my%20dataset%20and%20explain%20the%20results?"
        aria-label: "WhatsApp"
      - icon: facebook
        href: "https://web.facebook.com/profile.php?id=61582011403171"
        aria-label: "Facebook"

sidebar:
  - id: data
    title: "aaaa"
    style: "floating"
    collapse-level: 2
    align: left
    nav: data

format:
  html:
    theme: cosmo
    css: styles.css?v=2
    toc: true
    include-in-header: ga4.html